version: '3.8'

services:
  app:
    build:
      context: ./solmoi-express
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MYSQL_HOST=${{ secrets.MYSQL_HOST }}
      - MYSQL_PORT=${{ secrets.MYSQL_PORT }}
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
