name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Docker build and push
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build --platform linux/amd64 -t solmoi-express ./solmoi-express
        docker tag solmoi-express kimdongjae/gifted_dirac:${{ github.sha }}
        docker push kimdongjae/gifted_dirac:${{ github.sha }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Setup
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" | sed 's/\r$//' > ~/.ssh/solmoi-key.pem
        chmod 600 ~/.ssh/solmoi-key.pem
        ls -la ~/.ssh
        ssh-keyscan -H ec2-13-209-16-83.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        ssh -v -i ~/.ssh/solmoi-key.pem ubuntu@ec2-13-209-16-83.ap-northeast-2.compute.amazonaws.com "echo Connection successful"

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/solmoi-key.pem ubuntu@ec2-13-209-16-83.ap-northeast-2.compute.amazonaws.com "
        cd /home/ubuntu/Server &&
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
        MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
        MYSQL_USER=${{ secrets.MYSQL_USER }} \
        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
        MYSQL_HOST=db \
        MYSQL_PORT=3306 \
        docker-compose down -v || true &&
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
        MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
        MYSQL_USER=${{ secrets.MYSQL_USER }} \
        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
        MYSQL_HOST=db \
        MYSQL_PORT=3306 \
        docker-compose up -d --build
        "