name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Docker build and push
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build --platform linux/amd64 -t solmoi-express ./solmoi-express
        docker tag solmoi-express kimdongjae/gifted_dirac:${{ github.sha }}
        docker push kimdongjae/gifted_dirac:${{ github.sha }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > solmoi-key.pem
        chmod 600 solmoi-key.pem

    - name: Add EC2 host key
      run: |
        ssh-keyscan -H ec2-43-201-6-241.ap-northeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Create .env file on EC2
      run: |
        ssh -i solmoi-key.pem ubuntu@ec2-43-201-6-241.ap-northeast-2.compute.amazonaws.com "cat <<EOT > /home/ubuntu/Server/.env
        MYSQL_HOST=${{ secrets.MYSQL_HOST }}
        MYSQL_PORT=${{ secrets.MYSQL_PORT }}
        MYSQL_USER=${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        EOT"

    - name: Deploy to EC2
      run: |
        ssh -i solmoi-key.pem ubuntu@ec2-43-201-6-241.ap-northeast-2.compute.amazonaws.com "
        cd /home/ubuntu/Server &&
        docker-compose down -v || true &&
        docker-compose up -d --build
        "
