name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Change directory
      run: cd solmoi-express

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Docker build and push
      run: |
        cd solmoi-express
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        docker build --platform linux/amd64 -t solmoi-express .
        docker tag solmoi-express kimdongjae/gifted_dirac:${{ github.sha }}
        docker push kimdongjae/gifted_dirac:${{ github.sha }}